version: "0.1.5"
author: "ne0liberal"
root_dir: "D:/Content/ISOs"
completion_json: "D:/Content/index.json"
history_file: "D:/Content/history/history.json"
premium_dir: "premium"
is_dry_run: true
is_debug: true
do_imports: true
do_renames: true
do_renames_lowercase: true
do_converts: true
do_sanitize_filenames: true
do_remove_duplicate_extensions: true
do_premium_imports: true
do_loose_file_imports: true
do_image_converts: true
do_video_converts: true
do_import_coomer: true
do_import_fanhouse: true
do_import_fansly: true
do_import_gumroad: true
do_import_onlyfans: true
do_import_patreon: true
do_import_ppv: true
valid_filetypes:
  audio:
    - ".mp3"
    - ".wav"
    - ".flac"
    - ".m4a"
    - ".aac"
    - ".ogg"
  images:
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".bmp"
    - ".tiff"
    - ".webp"
    - ".jfif"
  text:
    - ".txt"
    - ".doc"
    - ".docx"
    - ".pdf"
    - ".rtf"
  misc:
    - ".zip"
    - ".rar"
    - ".7z"
    - ".torrent"
    - ".heic"
    - ".log"
    - ".db"
    - ".htm"
    - ".html"
    - ".bat"
    - ".py"
    - ".db-journal"
    - ".ini"
    - ".psd"
    - ".time"
  videos:
    - ".mp4"
    - ".mkv"
    - ".mov"
    - ".m4v"
    - ".wmv"
    - ".webm"
    - ".gif"
    - ".avi"
    - ".ts"
    - ".mpg"
    - ".flv"
    - ".mpeg"
goal_video_extension:
  - ".mp4"
  - ".webm"
  - ".gif"
goal_image_extension:
  - ".jpg"
  - ".webp"
protected_models:
  - "darshelle stevens"
  - "darshelle stevens - fix"
  - "darshelle - jessica - meg crossovers"
  - "jessica nigri"
  - "jessica nigri - fix"
  - "meg turney"
  - "meg turney - fix"
  - "virtual reality (vr)"
protected_dirs:
  - "corrupted"
  - "deepfakes"
  - "favorites"
  - "fix"
  - "manual_review"
  - "sorted albums"
  - "youtube"
